- name: Create DigitalOcean Droplet and Upload SSH Key
  hosts: localhost
  gather_facts: no
  vars_files:
    - secrets.yml
  roles:
    - provision_droplet

- name: Configure and Install Grafana on the Droplet
  hosts: grafana_droplet
  gather_facts: yes
  become: yes
  roles:
    - configure_grafana

